name: Build Modules

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_core_module:
    runs-on: macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Kotlin/Native Cache
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan

      - name: Build Core Module
        run: cd core/ && ./gradlew build

      - name: Test Core Module
        run: cd core/ && ./gradlew jvmTest