name: Main Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_publish_core_module:
    runs-on: macos-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Setup Gradle Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Change to the Core Module Directory
        run: cd core/

      - name: Build Core Module
        run: ./gradlew build

      - name: Publish Core Module Artifacts
        run: |
          echo "ghp.username=${{ github.actor }}\ngpr.token=${{ secrets.GITHUB_TOKEN }}" > gradle.properties
          ./gradlew publish